_wandb:
    value:
        cli_version: 0.24.0
        e:
            8uboqk3g1wv9ijfitjy90mybghnx0vjf:
                apple:
                    ecpuCores: 2
                    gpuCores: 16
                    memoryGb: 32
                    name: Apple M1 Pro
                    pcpuCores: 8
                    ramTotalBytes: "34359738368"
                    swapTotalBytes: "3221225472"
                args:
                    - --config
                    - /Users/willthompson/Documents/CSDS/side_projects/PythonForScientificDevelopment/configs/nlp_baseline.yaml
                    - --output
                    - results/nlp_baseline/adapter_dim~256/learning_rate~0.0001/model.pt
                    - --stats
                    - results/nlp_baseline/adapter_dim~256/learning_rate~0.0001/training_stats.parquet
                    - --adapter_dim
                    - "256"
                    - --learning_rate
                    - "0.0001"
                codePath: scripts/run_training.py
                codePathLocal: scripts/run_training.py
                cpu_count: 10
                cpu_count_logical: 10
                disk:
                    /:
                        total: "494384795648"
                        used: "482168057856"
                email: wthomps3@uvm.edu
                executable: /Users/willthompson/Documents/CSDS/side_projects/PythonForScientificDevelopment/.venv/bin/python3
                git:
                    commit: 555a4cb5d855323a44ca1d53c1fa2c533689f7b2
                    remote: https://github.com/WillHWThompson/PythonForScientificDevelopment.git
                host: Wills-MacBook-Pro-5.local
                memory:
                    total: "34359738368"
                os: macOS-14.6.1-arm64-arm-64bit
                program: /Users/willthompson/Documents/CSDS/side_projects/PythonForScientificDevelopment/scripts/run_training.py
                python: CPython 3.12.10
                root: /Users/willthompson/Documents/CSDS/side_projects/PythonForScientificDevelopment
                startedAt: "2026-01-24T18:19:15.102624Z"
                writerId: 8uboqk3g1wv9ijfitjy90mybghnx0vjf
        m: []
        python_version: 3.12.10
        t:
            "1":
                - 1
                - 5
                - 11
                - 12
                - 49
                - 51
                - 53
                - 100
            "2":
                - 1
                - 5
                - 11
                - 12
                - 49
                - 51
                - 53
                - 100
            "3":
                - 13
                - 16
            "4": 3.12.10
            "5": 0.24.0
            "6": 4.57.6
            "8":
                - 2
            "12": 0.24.0
            "13": darwin-arm64
data:
    value:
        dataset_name: ag_news
        max_samples: null
        train_split: train
        val_split: test
full_run_name:
    value: bert_topic_baseline_adim_256_lr_0.0001
model:
    value:
        adapter_dim: 256
        dropout: 0.1
        model_name: distilbert-base-uncased
        num_classes: 4
name:
    value: bert_topic_baseline
training:
    value:
        batch_size: 32
        epochs: 3
        learning_rate: 0.0001
        max_length: 128
        seed: 42
wandb_enabled:
    value: true
